variables:
  solution: 'YouthCenterSignIn.sln'

trigger:
  branches:
    include:
    - '*'  

stages:
  - stage: UnitTests
    jobs:
    - job: UnitTestsJob
      pool:
        vmImage: 'windows-latest'

      steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        inputs:
          solution: 'YouthCenterSignIn.sln'
          platform: 'x86'
          configuration: 'Debug'
          clean: true

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: 'YouthCenterSignIn.Logic.Tests\YouthCenterSignIn.Logic.Tests.csproj'


  - stage: ReleaseBuild
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
    - job: ReleaseBuildJob
      pool:
        vmImage: 'windows-latest'

      steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '$(solution)'
      - task: VSBuild@1
        inputs:
           solution: '$(solution)'
           platform: 'x86'
           configuration: 'Release'
           msbuildArgs: '/p:AppxBundlePlatforms="$(BuildPlatform)" /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppxPackages\\" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload -v:quiet'


  - stage: Deploy
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
    - job: DeployJob
      pool:
        vmImage: 'windows-latest'

      steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '$(solution)'
