# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'YouthCenterSignIn.sln'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    verbosityRestore: 'Normal'

- task: VSBuild@1
  inputs:
    solution: 'YouthCenterSignIn.sln'
    platform: 'x86'
    configuration: 'Debug'
    clean: true
    restoreNugetPackages: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'YouthCenterSignIn.Logic.Tests\YouthCenterSignIn.Logic.Tests.csproj'
